modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "foxified_classtweaker"
version = "${version}"
displayName = "FoxifiedClassTweaker"
authors = "CagayakeGirls, TexTrue"
description = '''
Provide Fabric's ClassTweaker support for FancyModLoader.
'''
logoFile = "assets/foxified_classtweaker/icon.png"

[[dependencies.foxified_classtweaker]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foxified_classtweaker]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[foxified.classtweaker]]
file = "example.classtweaker"
